name: Repository Dispatch

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Print event payload
      run: echo "${{ toJson(github.event.client_payload) }}"
